language: perl
dist: trusty
perl:
  - "5.26"
  - "5.26-shrplib"
  - "5.20"
  - "5.18-shrplib"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

install:
  - cpanm ExtUtils::MakeMaker
    # Because EUMM v6.66 doesn't seem to generate the correct MYMETA.json,
    # causing lib::relative not to be loaded as a dependency.  See, e.g.,
    # https://travis-ci.org/cxw42/Class-Tiny-ConstrainedAccessor/jobs/535823908
  - cpanm https://github.com/cxw42/Perl-vars-i/releases/download/v2.000000/vars-i-2.000000.tar.gz
    # Temporary, so I can run the test before vars::i 2.000000 is indexed.
    # TODO remove this at the next commit.
  - cpanm --with-recommends --verbose --installdeps --notest .
